org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

minecraft_version = 1.20.1
minecraft_version_range = [1.20.1, 1.21)
forge_version = 47.4.18
forge_version_range = [47,)
loader_version_range = [47,)

mapping_channel = parchment
mapping_version = 2023.09.03-1.20.1

mod_id = notjustspoiled
mod_name = Not Just Spoiled
mod_license = All Rights Reserved
mod_version = 0.1.0
mod_group_id = net.therealvoin.notjustspoiled
mod_authors = TheRealVoin
mod_description = Modern, lightweight and highly customizable mod that adds simple and interesting food spoilage mechanic